'use client';

import { useEffect, useState } from 'react';
import { AlertTriangle, CheckCircle, Clock, TrafficCone } from 'lucide-react';
import { api } from '@/lib/api-client';

interface Event { id: number; trackId: number; recommendedAction: string; confidence: number; safetyStatus: string; estimatedTimeSaved: number; queueImpact: number; reason: string; isDemo?: boolean; }
interface Insights { latestSession: { id: number; originalName: string } | null; metrics: { priorityEvents: number; timeSaved: number }; priorityEvents: Event[]; }

export default function SignalPriorityPage() {
  const [data, setData] = useState<Insights | null>(null);
  useEffect(() => { const load = async () => { try { setData(await api.get<Insights>('/api/insights')); } catch {} }; load(); const timer = setInterval(load, 3000); return () => clearInterval(timer); }, []);
  const event = data?.priorityEvents[0];
  const activeCount = data?.metrics.priorityEvents ?? 0;
  const saved = data?.metrics.timeSaved ?? 0;
  return <div className="space-y-6"><header><div className="flex flex-wrap items-center gap-3"><h1 className="text-3xl font-bold text-white">Signal Priority</h1><span className="rounded-full border border-yellow-400/30 bg-yellow-400/10 px-2.5 py-1 text-xs text-yellow-200">SIMULATION / RECOMMENDATION ONLY</span></div><p className="mt-2 text-slate-400">Safety-gated recommendation, never direct physical traffic-signal control</p>{data?.latestSession && <p className="mt-2 text-sm text-slate-300">CURRENT SESSION: <strong>{data.latestSession.id} · {data.latestSession.originalName}</strong></p>}</header><div className="grid grid-cols-1 md:grid-cols-4 gap-4"><Metric icon={TrafficCone} label="Priority Events" value={activeCount} /><Metric icon={Clock} label="Estimated Time Saved" value={`${saved}s`} /><Metric icon={CheckCircle} label="Safe Recommendations" value={activeCount && event?.safetyStatus === 'SAFE' ? 1 : 0} /><Metric icon={AlertTriangle} label="Withheld" value={activeCount && event?.recommendedAction === 'WITHHOLD' ? 1 : 0} /></div><section className="bg-slate-800 border border-slate-700 rounded-xl p-6"><h2 className="text-lg font-semibold text-white mb-4">Current Recommendation</h2>{event ? <div className="grid grid-cols-1 md:grid-cols-2 gap-4"><Info label="Event / Track" value={`${event.isDemo ? 'VIDEO-DERIVED SIMULATION' : `EVENT ${event.id}`} · TRACK-${event.trackId}`} /><Info label="Current signal" value="EAST-WEST GREEN" /><Info label="Recommended signal" value={`${event.recommendedAction} · ${getDirection(event.trackId)} GREEN`} valueClass="text-green-400" /><Info label="Affected approach" value={getDirection(event.trackId)} /><Info label="Safety status" value={event.safetyStatus} valueClass="text-green-400" /><Info label="Confidence / time saved" value={`${Math.round(event.confidence * 100)}% · ${event.estimatedTimeSaved}s`} /></div> : <div><p className="text-2xl text-cyan-400 font-bold">NORMAL SIGNAL</p><p className="mt-2 text-slate-400">Select a track and run the video-derived simulation to generate a recommendation.</p></div>}</section><section className="bg-slate-800 border border-slate-700 rounded-xl p-6"><h2 className="text-lg font-semibold text-white mb-4">Priority Recommendation</h2>{event ? <div className="border border-slate-700 rounded-lg p-4"><div className="flex flex-wrap justify-between gap-2"><span className="font-semibold text-white">{event.isDemo ? 'VIDEO-DERIVED SIMULATION' : `Event ${event.id}`} · Track {event.trackId}</span><span className={activeCount ? 'text-green-400' : 'text-yellow-200'}>{activeCount ? event.recommendedAction : 'READY'}</span></div><p className="mt-2 text-sm text-slate-400">{event.reason}</p><p className="mt-2 text-xs text-slate-500">Safety {event.safetyStatus} · Confidence {Math.round(event.confidence * 100)}% · Queue impact {event.queueImpact}</p></div> : <p className="py-8 text-center text-slate-400">No priority recommendation for the current session.</p>}</section></div>;
}
function getDirection(trackId: number) { return ['NORTH', 'SOUTH', 'EAST', 'WEST'][(trackId - 1) % 4]; }
function Info({ label, value, valueClass = 'text-white' }: { label: string; value: string; valueClass?: string }) { return <div className="rounded-lg border border-slate-700 bg-slate-900/40 p-3"><p className="text-xs text-slate-500">{label}</p><p className={`mt-1 font-semibold ${valueClass}`}>{value}</p></div>; }
function Metric({ icon: Icon, label, value }: { icon: any; label: string; value: string | number }) { return <div className="bg-slate-800 border border-slate-700 rounded-xl p-4"><Icon className="w-5 h-5 text-cyan-400 mb-3" /><div className="text-slate-400 text-sm">{label}</div><div className="text-2xl font-bold text-white">{value}</div></div>; }
