'use client';

import { useEffect, useState } from 'react';
import { List, RotateCcw } from 'lucide-react';
import { api } from '@/lib/api-client';

interface Log { timestamp: string; event: string; decision: string; action: string; source?: string; sessionId?: number; trackId?: number | null; }
interface Insights { latestSession: { id: number; originalName: string } | null; decisionLogs: Log[]; }

export default function DecisionLogPage() {
  const [data, setData] = useState<Insights | null>(null);
  useEffect(() => { const load = async () => { try { setData(await api.get<Insights>('/api/insights')); } catch {} }; load(); const timer = setInterval(load, 2500); return () => clearInterval(timer); }, []);
  return <div className="space-y-6"><div><h1 className="text-3xl font-bold text-white mb-2">Decision Log</h1><p className="text-slate-400">Chronological actions generated by the current processing session</p>{data?.latestSession && <p className="mt-2 text-sm text-slate-300">CURRENT SESSION: <strong>{data.latestSession.id} · {data.latestSession.originalName}</strong></p>}</div><section className="bg-slate-800 border border-slate-700 rounded-xl p-6"><h2 className="text-lg font-semibold text-white flex items-center gap-2 mb-4"><List className="w-5 h-5 text-cyan-400" />Session Events</h2>{data?.decisionLogs.length ? <div className="space-y-3">{data.decisionLogs.map((log, index) => <article key={`${log.timestamp}-${index}`} className="grid grid-cols-1 gap-2 rounded-lg border border-slate-700 p-4 md:grid-cols-[150px_1.2fr_120px_140px_2fr]"><time className="text-xs text-slate-500">{new Date(log.timestamp).toLocaleTimeString()}</time><div><p className="font-semibold text-white">{log.event}</p><p className="text-xs text-slate-500">Session {log.sessionId ?? data.latestSession?.id}{log.trackId ? ` · Track ${log.trackId}` : ''}</p></div><span className="text-xs font-semibold text-cyan-300">{log.decision}</span><span className="text-xs text-yellow-200">{log.source ?? 'SYSTEM'}</span><p className="text-sm text-slate-400">{log.action}</p></article>)}</div> : <div className="py-10 text-center text-slate-400"><RotateCcw className="mx-auto mb-3 h-8 w-8 text-slate-600" /><p>No current-session events yet.</p><p className="mt-1 text-sm">Upload and process a video to create the session timeline.</p></div>}</section></div>;
}
